### ISSUE TITLE
Request: Assign embed/message to add SendSelectionAsync's emotes to.

### ISSUE THREAD

**Issue by stageosu** [Playwo/Discord.InteractivityAddon#8]
I am currently writing a command that needs input from the user (a selection from 5 choices). I have created my own custom embed and stored that as a `RestUserMessage` that could ideally be modified by the `SendSelectionAsync()` method of the interactivity service.

As of right now, if you pass in an `IUserMessage` into this method, the contents of that message are erased and replaced with whatever the builder is using (in my experience, it's an empty embed when `.WithEnableDefaultSelectionDescription(false)` is set.

In the following codeblock, `var result = await _interactivityService.SendSelectionAsync(builder.Build(), Context.Channel, TimeSpan.FromMinutes(2), toModify);` will set the contents of `toModify` to something else. This request is asking for the contents of `toModify` to be left unchanged and for the emotes to be added to the `toModify` message directly. (I'm also not sure if it's intended for `toModify` to be overwritten by `SendSelectionAsync()`).

Ideally, this should add reactions to `toModify` instead of changing it's contents:
```cs
var embed = new KaguyaEmbedBuilder(Color.Blue)
            .WithTitle("Kaguya Music: Search Result")
            .WithDescription($"{Context.User.Mention} {line1}")
            .WithFields(embedFields);

var toModify = await SendEmbedAsync(embed);
var builder = new ReactionSelectionBuilder<int>()
                .WithValues(0, 1, 2, 3, 4)
                .WithEmotes(_commonEmotes.EmojisOneThroughFive)
                .WithEnableDefaultSelectionDescription(false)
                .WithDeletion(DeletionOptions.AfterCapturedContext | DeletionOptions.Invalids)
                .WithUsers(Context.User);

var result = await _interactivityService.SendSelectionAsync(builder.Build(), Context.Channel, TimeSpan.FromMinutes(2), toModify);
```

**Comment by Playwo** [comment]
I do see where this could be useful. I'm not sure on how to add it properly yet. Maybe another option for the Selection. Another idea would be to keep the old message if there is no embed provided. But just removing the modification of the message is not how I would want to do it. Ill think about it and will let you know when I decided how I want to implement it.

**Comment by Playwo** [comment]
I've decided that this behavior should not be covered by the current implementation of Selection. Unfortunately the Selection baseclass is currently not "powerful" enough to allow you to make your own implementation that does just that. I'll change the signature of the baseclass to allow for that in the next few days.

**Comment by stageosu** [comment]
> I've decided that this behavior should not be covered by the current implementation of Selection. Unfortunately the Selection baseclass is currently not "powerful" enough to allow you to make your own implementation that does just that. I'll change the signature of the baseclass to allow for that in the next few days. 

Sounds good, thanks :).

**Comment by Playwo** [comment]
I have pushed a change right now that should allow you to do it now. Please give it a try because there are probably some bugs.

**Comment by stageosu** [comment]
> I have pushed a change right now that should allow you to do it now. Please give it a try because there are probably some bugs.

Will do sometime today or tomorrow and I'll let you know.

**Comment by Playwo** [comment]
I've just noticed that nuget does not consider rc10 the latest version for some reason. "Downgrade" to rc10 to test it

**Comment by stageosu** [comment]
> I've just noticed that nuget does not consider rc10 the latest version for some reason. "Downgrade" to rc10 to test it

Nuget still showing rc9 as latest on my end.
<img width="868" alt="Screen Shot 2021-01-25 at 9 41 44 AM" src="https://user-images.githubusercontent.com/38370573/105720545-8b2c5600-5ef1-11eb-8b63-0e3b5b0ca097.png">

**Comment by Playwo** [comment]
Yeah that's what I meant. rc10 is below rc2 but it is the latest version. I want to change the versioning soon but until then you gotta live with that :/

**Comment by stageosu** [comment]
Haha, ahh. I see why it did that now, that's funny. I had assumed it would be under rc9 - I should've scrolled down some! #13 will be a welcomed change. Testing now, will let you know what happens.

**Comment by Playwo** [comment]
At least no one will use the likely unstable version now... xD

**Comment by stageosu** [comment]
Did exactly what I expected, but it still edited my message?

__Try 1:__
I sent my embed, the embed was sent properly, then edited (to an empty embed very fast? I couldn't tell), then edited back to my original embed.

__Try 2:__
Okay, weird...edited to an empty embed and it stayed this time? 

https://user-images.githubusercontent.com/38370573/105727411-0cd3b200-5ef9-11eb-8764-e46891f927f0.mp4

__Try 3:__
Same as try 2

https://user-images.githubusercontent.com/38370573/105727508-28d75380-5ef9-11eb-9509-f9f3a0258a15.mp4


__Code:__
```cs
var toModify = await SendEmbedAsync(embed);
var builder = new ReactionSelectionBuilder<int>()
                .WithSelectables(new Dictionary<IEmote, int>
                {
                    { _commonEmotes.EmojisOneThroughFive[0], 0 },
                    { _commonEmotes.EmojisOneThroughFive[1], 1 },
                    { _commonEmotes.EmojisOneThroughFive[2], 2 },
                    { _commonEmotes.EmojisOneThroughFive[3], 3 },
                    { _commonEmotes.EmojisOneThroughFive[4], 4 }
                })
                .WithEnableDefaultSelectionDescription(false)
                .WithDeletion(DeletionOptions.AfterCapturedContext | DeletionOptions.Invalids)
                .WithUsers(Context.User);

var result = await _interactivityService.SendSelectionAsync(builder.Build(), Context.Channel, TimeSpan.FromMinutes(2), toModify);

if (result.IsSuccess)
{ ... }
```

**Comment by Playwo** [comment]
> I've decided that this behavior should not be covered by the current implementation of Selection. Unfortunately the Selection baseclass is currently not "powerful" enough to allow you to make your own implementation that does just that. I'll change the signature of the baseclass to allow for that in the next few days.

My change does not really affect the "default" reaction selection (hopefully) but it allows you to make your own one. 
Create a child class of BaseReactionSelection and BaseReactionSelectionBuilder and implement what you need. (Basically remove everything you don't need from the [default implementation ](https://github.com/Playwo/Discord.InteractivityAddon/blob/main/InteractivityAddon/Selection/Reaction/ReactionSelection.cs)

**Comment by stageosu** [comment]
Ah okay, I will get started on a base class sometime today and I will let you know how that goes. Thanks :)

**Comment by stageosu** [comment]
Sorry for getting back to you just now about this. I've been super busy. Working on it right now and will update you soon.

**Comment by stageosu** [comment]
I may be missing the point, but do I need to re-implement these classes in full? i.e. copy the code in the `BaseReactionSelection` and `BaseReactionSelectionBuilder` classes and strip what I don't need? I'm just pretty confused - all I really care about is the behavior of `SendSelectionAsync()`.

**Comment by Playwo** [comment]
Jep that is exactly the point of that change. It should be relatively simple to do

**Comment by stageosu** [comment]
Gotcha, so I've got your code copied down into two custom classes (basically, copy-pasting from your ReactionSelection and ReactionSelectionBuilder classes). Not sure if this is the right way to do this, but I assumed the `ModifyMessageAsync` method is responsible for editing the embed. I changed the code to just return a completed task so that it wouldn't modify the message passed in, but the embed was still modified. I'm wondering how I can change the behavior such that when a message is sent, I can keep it from being modified elsewhere.

**Comment by Playwo** [comment]
`ModifyMessageAsync` is the correct one to change. If it is still modifying the message you are likely still passing a instance of the other Selection to `SendSelectionAsync`. You need to instanciate your own one (Could be useful to also copy the builder)

**Comment by stageosu** [comment]
Mind taking a look? I don't know what else I can change.

**Code**
[Usage](https://gist.github.com/stageosu/f9e8b3bfafaa34cf110267600de27689)
[KaguyaReactionSelectionBuilder](https://gist.github.com/stageosu/4b2829b3753dd47cf4747c8907d7a450)
[KaguyaReactionSelection](https://gist.github.com/stageosu/063766b25808aaadb79086c9da9733fd) (Line 74)

I ensured I am casting to a `KaguyaReactionSelection<int>`, which has a `ModifyMessageAsync` task that just returns a completed task. Is there something I am missing?

**Comment by stageosu** [comment]
> Mind taking a look? I don't know what else I can change.
> 
> **Code**
> [Usage](https://gist.github.com/stageosu/f9e8b3bfafaa34cf110267600de27689)
> [KaguyaReactionSelectionBuilder](https://gist.github.com/stageosu/4b2829b3753dd47cf4747c8907d7a450)
> [KaguyaReactionSelection](https://gist.github.com/stageosu/063766b25808aaadb79086c9da9733fd) (Line 74)
> 
> I ensured I am casting to a `KaguyaReactionSelection<int>`, which has a `ModifyMessageAsync` task that just returns a completed task. Is there something I am missing?

I will also note the response from this code:
![](https://i.imgur.com/DxPnKvJ.png)

Exception:
```
[01-30-2021 14:56:36:518] fail: Kaguya.Workers.DiscordWorker[0]
      Exception encountered when executing command. Message:
      Discord.Commands.CommandException: Error occurred executing "SearchCommand" for Stage#0001 in Kaguya Testing/general.
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Interactivity.InteractivityService.SendSelectionAsync[TValue](BaseReactionSelection`1 selection, IMessageChannel channel, Nullable`1 timeout, IUserMessage message, CancellationToken cancellationToken)
         at Kaguya.Discord.Commands.Music.Search.SearchCommand(String search) in C:\Users\stage\Documents\GitHub\Kaguya\Kaguya\Kaguya\Discord\Commands\Music\Search.cs:line 116
         at Discord.Commands.ModuleClassBuilder.<>c__DisplayClass6_0.<<BuildCommand>g__ExecuteCallback|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Discord.Commands.CommandInfo.ExecuteInternalAsync(ICommandContext context, Object[] args, IServiceProvider services)
         --- End of inner exception stack trace ---
```

**Comment by Playwo** [comment]
Your `KaguyaReactionSelectionBuilder` is still returning a `ReactionSelection` ([Code](https://gist.github.com/stageosu/4b2829b3753dd47cf4747c8907d7a450#file-kaguyareactionselectionbuilder-cs-L108-L117))
That is causing this [cast](https://gist.github.com/stageosu/f9e8b3bfafaa34cf110267600de27689#file-search-cs-L20) to return null which is the  reason for the NullRef
Well and you kinda missed the point of having your own implementation. You can remove most of the code in the builder and selection because you are not using it anyway.

**Comment by stageosu** [comment]
Okay, I figured as such, I only hard casted because w/o the cast it still edits the message. And good to know about your first comment......I feel a little dumb.

Once I fix that I'll remove the excess copied code that is already used by the OG base class. Thanks lol.

**Comment by stageosu** [comment]
Yep, changing [this](https://gist.github.com/stageosu/4b2829b3753dd47cf4747c8907d7a450#file-kaguyareactionselectionbuilder-cs-L108-L117) to the correct type fixes the issue.

Thank you for working with me on this Playwo :)
